version: '3'
services:
  api:
    container_name: api
    build: .
    expose:
      - 5000

  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
